$base = "D:\GitHub\LumeOS-Claude-V1"

$dirs = @(
  "docs\specs",
  "docs\decisions",
  "docs\architecture",
  "docs\reports",
  "docs\runbooks",
  "docs\stack",
  "docs\memory",
  "system\workorders\lifecycle",
  "system\workorders\batches",
  "system\workorders\templates",
  "system\workorders\schemas",
  "system\decomposition\specs",
  "system\decomposition\schemas",
  "system\decomposition\validators",
  "system\agent-registry",
  "system\file-groups",
  "system\scheduler",
  "system\graph",
  "system\policies\gsd-v2",
  "system\policies\retry",
  "system\policies\guardrails",
  "system\policies\review",
  "system\policies\promotion",
  "system\prompts\gstack",
  "system\prompts\wo-factory",
  "system\prompts\review",
  "system\prompts\orchestration",
  "system\memory\schemas",
  "system\memory\events",
  "system\memory\execution",
  "system\memory\learning",
  "system\memory\promotions",
  "system\memory\retrieval",
  "system\memory\canonical",
  "system\branch-policy",
  "system\db-environments",
  "system\model-tiers",
  "system\control-plane",
  "infra\docker",
  "infra\caddy",
  "infra\coolify",
  "infra\paperclip",
  "infra\qdrant",
  "infra\vllm\spark-a",
  "infra\vllm\spark-b",
  "infra\vllm\profiles",
  "infra\openrouter",
  "infra\supabase",
  "infra\monitoring",
  "infra\logging",
  "infra\secrets",
  "tools\serena",
  "tools\rtk",
  "tools\gstack",
  "tools\paperclip",
  "tools\qdrant",
  "tools\obsidian",
  "tools\ingestion",
  "tools\scripts",
  "tools\validators",
  "tools\migrations",
  "tools\bootstrap",
  ".github\workflows",
  ".github\ISSUE_TEMPLATE",
  ".github\branch-protection"
)

foreach ($d in $dirs) {
  New-Item -ItemType Directory -Force -Path "$base\$d" | Out-Null
}
Write-Host "Phase 2 done: docs / system / infra / tools / .github"
