$base = "D:\GitHub\LumeOS-Claude-V1"

$dirs = @(
  "apps\web\src\app",
  "apps\web\src\features\nutrition",
  "apps\web\src\features\training",
  "apps\web\src\features\supplements",
  "apps\web\src\features\recovery",
  "apps\web\src\features\goals",
  "apps\web\src\features\coach",
  "apps\web\src\features\medical",
  "apps\web\src\features\marketplace",
  "apps\web\src\components",
  "apps\web\src\hooks",
  "apps\admin\src",
  "apps\buddy\src",
  "apps\coach\src",
  "apps\staff\src",
  "apps\mobile\src",
  "services\nutrition-api\src",
  "services\training-api\src",
  "services\supplements-api\src",
  "services\recovery-api\src",
  "services\coach-api\src",
  "services\medical-api\src",
  "services\goals-api\src",
  "services\marketplace-api\src",
  "services\memory-api\src",
  "services\analytics-api\src",
  "services\auth-api\src",
  "services\admin-api\src",
  "services\retrieval-api\src",
  "services\orchestrator-api\src",
  "packages\types\src",
  "packages\contracts\src",
  "packages\shared\src",
  "packages\config\src",
  "packages\ui\src",
  "packages\rules\src",
  "packages\skills\src",
  "packages\prompts\src",
  "packages\wo-core\src",
  "packages\graph-core\src",
  "packages\scheduler-core\src",
  "packages\agent-core\src",
  "packages\memory-core\src",
  "packages\retrieval-core\src",
  "packages\tool-adapters\src",
  "packages\branch-db-core\src",
  "db\migrations",
  "db\schema",
  "db\seeds",
  "db\contracts",
  "db\local-dev",
  "db\local-main",
  "db\remote-dev",
  "db\remote-main"
)

foreach ($d in $dirs) {
  New-Item -ItemType Directory -Force -Path "$base\$d" | Out-Null
}
Write-Host "Phase 1 done: apps / services / packages / db"
