import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 1400 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=plans', { waitUntil: 'networkidle' })
await s.waitForTimeout(2500)
const ring = s.locator('.v2-ring').first()
const rb = await ring.boundingBox()
const svg = await ring.locator('svg').boundingBox()
const v = await s.locator('.v2-ring-label .v2-v').first().boundingBox()
const l = await s.locator('.v2-ring-label .v2-l').first().boundingBox()
console.log(`Ring  y ${Math.round(rb.y)}..${Math.round(rb.y+rb.height)}  h=${Math.round(rb.height)}`)
console.log(`SVG   y ${Math.round(svg.y)}..${Math.round(svg.y+svg.height)}`)
console.log(`Wert  y ${Math.round(v.y)}..${Math.round(v.y+v.height)}  h=${Math.round(v.height)}`)
console.log(`Label y ${Math.round(l.y)}..${Math.round(l.y+l.height)}  h=${Math.round(l.height)} w=${Math.round(l.width)}`)
console.log('')
console.log(`Label INNERHALB des Rings: ${l.y < rb.y + rb.height ? 'JA -- es liegt im Kreis' : 'nein'}`)
console.log(`Wert+Label zusammen: ${Math.round(v.height + l.height)}px in ${Math.round(rb.height)}px Ring`)
await b.close()
