import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 1700 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=planner', { waitUntil: 'networkidle' })
await s.waitForTimeout(2600)
await s.locator('button[aria-label^="Eintrag hinzufügen"]').first().click()
await s.waitForTimeout(900)
await s.locator('select').filter({ hasText: 'Rezept' }).first().selectOption('bls')
await s.waitForTimeout(500)
await s.getByRole('button', { name: /Suchen/ }).first().click()
await s.waitForTimeout(700)
await s.fill('[role="dialog"] input[aria-label="Lebensmittel suchen"]', 'hammel')
await s.waitForTimeout(1800)
// Die erste Zeile im Ganzen: Name und die kcal-Spalte je 100 g.
const z = s.locator('[role="dialog"] tbody tr').first()
console.log('Zeile 1:', JSON.stringify((await z.innerText()).replace(/\n/g, ' | ')))
await z.locator('button').click()
await s.waitForTimeout(1200)
console.log('gewaehlt:', JSON.stringify((await s.locator('[role="dialog"]').innerText()).split('\n').slice(0,6).join(' | ')))
const mengeFeld = s.locator('[role="dialog"] input[aria-label="Menge in Gramm"]')
console.log('Vorgabemenge:', await mengeFeld.inputValue())
await mengeFeld.fill('150')
await s.waitForTimeout(600)
console.log('bei 150 g:', JSON.stringify((await s.locator('[data-probe="vorschau"]').innerText()).replace(/\n/g, ' ')))
await b.close()
