import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 1700 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=planner', { waitUntil: 'networkidle' })
await s.waitForTimeout(2600)
await s.locator('button[aria-label^="Eintrag hinzufügen"]').first().click()
await s.waitForTimeout(900)
await s.locator('select').filter({ hasText: 'Rezept' }).first().selectOption('bls')
await s.waitForTimeout(500)
await s.getByRole('button', { name: /Suchen/ }).first().click()
await s.waitForTimeout(700)
await s.fill('[role="dialog"] input[aria-label="Lebensmittel suchen"]', 'banane')
await s.waitForTimeout(2200)

const tab = s.locator('[role="dialog"] table')
console.log(`Treffer: ${await s.locator('[role="dialog"] tbody tr').count()}`)
console.log(`Trefferzahl: ${await s.locator('[data-probe="trefferzahl"]').innerText().catch(()=>'—')}`)
console.log(`table display: ${await tab.evaluate(n => getComputedStyle(n).display)}`)
console.log(`table class:   ${await tab.getAttribute('class')}`)
// Wo steht der Kopf, wo die erste Zeile?
const kopf = await s.locator('[role="dialog"] thead').boundingBox()
const z1   = await s.locator('[role="dialog"] tbody tr').first().boundingBox()
const z8   = await s.locator('[role="dialog"] tbody tr').nth(7).boundingBox().catch(()=>null)
console.log(`thead   y=${kopf?.y.toFixed(0)} x=${kopf?.x.toFixed(0)} h=${kopf?.height.toFixed(0)}`)
console.log(`Zeile 1 y=${z1?.y.toFixed(0)} x=${z1?.x.toFixed(0)}`)
if (z8) console.log(`Zeile 8 y=${z8.y.toFixed(0)}`)
console.log(`Kopf UEBER Zeile 1: ${kopf && z1 && kopf.y < z1.y ? 'ja' : 'NEIN — der Spaltenfehler'}`)
// Laeuft die Tabelle waagerecht?
const huelle = s.locator('[role="dialog"] div').filter({ has: s.locator('table') }).last()
console.log(`waagerechter Ueberlauf: ${await huelle.evaluate(n => n.scrollWidth - n.clientWidth)} px`)
// Sind die Werte getrennt?
const z = s.locator('[role="dialog"] tbody tr').first()
console.log(`Zeile-1-Text: ${JSON.stringify((await z.innerText()).replace(/\n/g,' | '))}`)
console.log(`Zellen in Zeile 1: ${await z.locator('td').count()}`)
await s.screenshot({ path: 'backup/g321-vorher.png' })
await b.close()
