import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 1700 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=recipes', { waitUntil: 'networkidle' })
await s.waitForTimeout(2600)
const alle = await s.locator('button').allInnerTexts()
console.log('Knoepfe auf der Seite:', JSON.stringify([...new Set(alle.map(x=>x.trim()).filter(Boolean))].slice(0,14)))
const labels = await s.locator('button[aria-label]').evaluateAll(ns => ns.map(n => n.getAttribute('aria-label')).slice(0,14))
console.log('aria-labels:', JSON.stringify(labels))
console.log('Mengenfelder VOR Klick:', await s.locator('input[aria-label^="Menge "]').count())
await b.close()
