import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 2200 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=diary', { waitUntil: 'networkidle' })
await s.waitForTimeout(2800)
const t = await s.locator('body').innerText()
const z = t.split('\n').map(x => x.trim()).filter(Boolean)
const i = z.findIndex(x => /^\d\d:\d\d$/.test(x) || x.includes('Breakfast'))
console.log('── Diary, ab der ersten Mahlzeit ──')
z.slice(Math.max(0, i - 2), i + 26).forEach(x => console.log(`  ${JSON.stringify(x)}`))
console.log('\n── Ghost-Karten ──')
console.log(`Ghost-Marken: ${await s.getByText('Ghost').count()}`)
const g = z.findIndex(x => x.toLowerCase().includes('ghost'))
if (g >= 0) z.slice(g, g + 16).forEach(x => console.log(`  ${JSON.stringify(x)}`))
await s.screenshot({ path: 'backup/g329-vorher.png', fullPage: true })
await b.close()
