import { chromium } from '@playwright/test'
import { wortFuer } from '../tools/konten.mjs'
const b = await chromium.launch()
const s = await b.newPage({ viewport: { width: 1440, height: 2400 } })
await s.goto('http://127.0.0.1:3200/login', { waitUntil: 'networkidle' })
await s.fill('input[type="email"]', 'dev@lumeos.app')
await s.fill('input[type="password"]', wortFuer('dev@lumeos.app'))
await s.click('button[type="submit"]')
await s.waitForURL(u => !u.pathname.includes('login'), { timeout: 30000 })
await s.goto('http://127.0.0.1:3200/v2/nutrition?tab=prefs', { waitUntil: 'networkidle' })
await s.waitForTimeout(4000)
const n = s.locator('[data-probe="planner-notes"]')
console.log(`Feld da: ${await n.count()}`)
console.log(`value:       ${JSON.stringify(await n.inputValue())}`)
console.log(`defaultValue:${JSON.stringify(await n.evaluate(x => x.defaultValue))}`)
console.log(`textContent: ${JSON.stringify(await n.evaluate(x => x.textContent))}`)
await b.close()
