// Die Zahlen von Auswertung, Regeln, Team und Umsatz — G-407.
// 
// ABGELESEN, NICHT ERFUNDEN. Quellen:
//   module-coach-extras.jsx  AUTONOMY_LEVELS, RULE_*, ACTIVE_RULES,
//                            SMART_ALERTS, COACH_ROLES, TEAM_MEMBERS,
//                            COACH_AUDIT, COACH_KPIS
//   module-coach.jsx         COACHES, PENDING_INVITES, COACH_NOTES,
//                            PORTAL_ATHLETES, COACH_PLANS, MESSAGES_THREAD

/** `extras.jsx` · `AUTONOMY_LEVELS` */
export const AUTONOMY_LEVELS = [
    {
      lvl: 1,
      key: "novice",
      name: "Novice",
      desc: "Hand-holding · daily guidance · strict adherence",
      cadence: "daily",
      style: "directive",
      threshold: "any deviation",
    },
    {
      lvl: 2,
      key: "beginner",
      name: "Beginner",
      desc: "Learning · weekly check-ins · structured plans",
      cadence: "weekly",
      style: "guided",
      threshold: "significant deviation",
    },
    {
      lvl: 3,
      key: "intermediate",
      name: "Intermediate",
      desc: "Growing · bi-weekly reviews · guided flexibility",
      cadence: "bi-weekly",
      style: "collaborative",
      threshold: "significant trends",
    },
    {
      lvl: 4,
      key: "advanced",
      name: "Advanced",
      desc: "Self-directed · monthly coaching · high independence",
      cadence: "monthly",
      style: "consultative",
      threshold: "warning signs only",
    },
    {
      lvl: 5,
      key: "expert",
      name: "Expert",
      desc: "Mentor-ready · quarterly reviews · peer mentoring",
      cadence: "quarterly",
      style: "advisory",
      threshold: "safety only",
    },
  ] as const

/** `extras.jsx` · `ATHLETE_AUTONOMY` */
export const ATHLETE_AUTONOMY = {
    a1: {
      level: 4,
      trend: "stable",
      since: "8mo",
      canProgress: true,
      recommendation: "Hold · stable at Advanced for 8 months",
    },
    a2: {
      level: 2,
      trend: "up",
      since: "2mo",
      canProgress: true,
      recommendation: "Ready to progress to Intermediate · 3 weeks of stability",
    },
    a3: {
      level: 5,
      trend: "stable",
      since: "1y",
      canProgress: false,
      recommendation: "Top of framework · mentor candidate",
    },
    a4: {
      level: 1,
      trend: "stable",
      since: "3mo",
      canProgress: false,
      recommendation: "Hold · still learning fundamentals",
    },
    a5: {
      level: 4,
      trend: "stable",
      since: "10mo",
      canProgress: true,
      recommendation: "Stable · could promote with more structured planning",
    },
    a6: {
      level: 3,
      trend: "up",
      since: "5mo",
      canProgress: false,
      recommendation: "Progressing well · 2 months from next level",
    },
    a7: {
      level: 2,
      trend: "down",
      since: "4mo",
      canProgress: false,
      recommendation: "Regression risk · compliance dropped 12pp",
    },
    a8: {
      level: 3,
      trend: "stable",
      since: "2mo",
      canProgress: false,
      recommendation: "Building consistency at Intermediate",
    },
    a9: {
      level: 4,
      trend: "stable",
      since: "1y",
      canProgress: false,
      recommendation: "Comfortable at Advanced",
    },
    a10: {
      level: 2,
      trend: "down",
      since: "3mo",
      canProgress: false,
      recommendation: "Watch · stability score dropping",
    },
    a11: {
      level: 4,
      trend: "up",
      since: "2y",
      canProgress: true,
      recommendation: "Endurance specialist · could progress to Expert",
    },
    a12: {
      level: 2,
      trend: "stable",
      since: "6mo",
      canProgress: false,
      recommendation: "Comfortable Beginner · no rush",
    },
    a13: {
      level: 4,
      trend: "up",
      since: "8mo",
      canProgress: true,
      recommendation: "Self-driven · primed for Expert",
    },
    a14: {
      level: 1,
      trend: "up",
      since: "2mo",
      canProgress: false,
      recommendation: "Promising start · check in 4 more weeks",
    },
  } as const

/** `extras.jsx` · `RULE_TRIGGERS` */
export const RULE_TRIGGERS = [
    {
      id: "threshold",
      label: "Data threshold",
      icon: "trend_up",
      desc: "When a metric crosses a value",
    },
    {
      id: "trend",
      label: "Trend detection",
      icon: "trend_up",
      desc: "When a trend changes direction",
    },
    { id: "time", label: "Time-based", icon: "calendar", desc: "On schedule or deadline" },
    { id: "event", label: "Event-based", icon: "bolt", desc: "When a specific event occurs" },
    { id: "compare", label: "Comparison", icon: "layers", desc: "Versus baseline or peer" },
  ] as const

/** `extras.jsx` · `RULE_TEMPLATES` */
export const RULE_TEMPLATES = [
    {
      id: "t1",
      name: "Adherence decline detection",
      cat: "Nutrition",
      diff: "beginner",
      downloads: 412,
      rating: 4.8,
      desc: "Alerts when nutrition adherence drops 15+ points in any 7-day window",
    },
    {
      id: "t2",
      name: "Overtraining risk · 3-strike",
      cat: "Training",
      diff: "advanced",
      downloads: 286,
      rating: 4.9,
      desc: "Recovery < 65 + sleep < 6h + RPE > 8 over 3 days = critical alert",
    },
    {
      id: "t3",
      name: "Plateau identification",
      cat: "Training",
      diff: "intermediate",
      downloads: 198,
      rating: 4.7,
      desc: "PR detection stalled for 14 days, suggests deload",
    },
    {
      id: "t4",
      name: "Goal deadline reminder",
      cat: "General",
      diff: "beginner",
      downloads: 540,
      rating: 4.6,
      desc: "30/7/2 day warnings before goal deadline if {`<`} 70% complete",
    },
    {
      id: "t5",
      name: "Achievement celebration",
      cat: "General",
      diff: "beginner",
      downloads: 380,
      rating: 4.5,
      desc: "Auto-celebrate PRs, streaks, milestones · client + coach notified",
    },
    {
      id: "t6",
      name: "Sleep-debt accumulation",
      cat: "Recovery",
      diff: "intermediate",
      downloads: 144,
      rating: 4.7,
      desc: "Cumulative sleep debt > 4 hours over 7 days triggers wellness check",
    },
  ] as const

/** `extras.jsx` · `ACTIVE_RULES` */
export const ACTIVE_RULES = [
    {
      id: "r1",
      name: "Overtraining risk",
      template: "t2",
      assignedTo: 11,
      fired: 3,
      falsePositives: 0,
      lastFired: "today 06:14",
      active: true,
      severity: "CRITICAL",
    },
    {
      id: "r2",
      name: "Adherence decline (nutrition)",
      template: "t1",
      assignedTo: 14,
      fired: 8,
      falsePositives: 1,
      lastFired: "yesterday 11:30",
      active: true,
      severity: "HIGH",
    },
    {
      id: "r3",
      name: "Missed sessions · 2x in a week",
      template: null,
      assignedTo: 14,
      fired: 4,
      falsePositives: 0,
      lastFired: "Mon",
      active: true,
      severity: "MEDIUM",
    },
    {
      id: "r4",
      name: "PR celebration",
      template: "t5",
      assignedTo: 14,
      fired: 12,
      falsePositives: 0,
      lastFired: "today 06:30",
      active: true,
      severity: "INFO",
    },
    {
      id: "r5",
      name: "Goal deadline · 7d warning",
      template: "t4",
      assignedTo: 8,
      fired: 2,
      falsePositives: 0,
      lastFired: "Tue",
      active: true,
      severity: "LOW",
    },
    {
      id: "r6",
      name: "Sleep debt",
      template: "t6",
      assignedTo: 14,
      fired: 1,
      falsePositives: 0,
      lastFired: "Apr 28",
      active: false,
      severity: "MEDIUM",
    },
  ] as const

/** `extras.jsx` · `SMART_ALERTS` */
export const SMART_ALERTS = [
    {
      id: "AL-018",
      severity: "CRITICAL",
      athlete: "Sophie Klein",
      aid: "a2",
      type: "Overtraining risk",
      title: "3-day pattern · recovery 58 + sleep 5.8h + RPE 8.5",
      why: "Sophie\u0027s combined metrics breached the Overtraining Risk rule for 3 consecutive days.",
      confidence: 0.91,
      fpRisk: 0.04,
      predicted: "Performance decline + injury risk if pattern continues 7+ days",
      similarCases: 4,
      age: "12m ago",
      expires: "in 4h",
    },
    {
      id: "AL-017",
      severity: "HIGH",
      athlete: "Elena Schmidt",
      aid: "a4",
      type: "Adherence decline",
      title: "Nutrition adherence dropped to 62% (was 82%)",
      why: "7-day moving average fell 20pp. Coincides with travel period (Apr 28 → May 4).",
      confidence: 0.78,
      fpRisk: 0.12,
      predicted: "Stalled body-comp goal · regression risk for autonomy level",
      similarCases: 11,
      age: "1h ago",
      expires: "in 23h",
    },
    {
      id: "AL-016",
      severity: "HIGH",
      athlete: "Daniel Vogel",
      aid: "a9",
      type: "Missed sessions",
      title: "2 sessions missed in current week (Wed, Sat)",
      why: "Pattern · skipped accessory work in Block 2. RPE on logged sessions 9.2 (high).",
      confidence: 0.84,
      fpRisk: 0.08,
      predicted: "Linear regression incomplete · risks plateau",
      similarCases: 3,
      age: "3h ago",
    },
    {
      id: "AL-015",
      severity: "MEDIUM",
      athlete: "Mira Stahl",
      aid: "a10",
      type: "Sleep-debt",
      title: "Cumulative sleep debt 5.2h over 7 days",
      why: "5 nights below 6.5h. Recovery score correlated drop (78 → 64).",
      confidence: 0.72,
      fpRisk: 0.15,
      predicted: "Compounding fatigue, may affect Wed PR attempt",
      similarCases: 7,
      age: "5h ago",
    },
    {
      id: "AL-014",
      severity: "MEDIUM",
      athlete: "Anna Frey",
      aid: "a12",
      type: "Compliance",
      title: "Compliance trending down 4 weeks (92 → 79)",
      why: "Gradual decline · no single event. Communication frequency also down.",
      confidence: 0.66,
      fpRisk: 0.22,
      predicted: "Possible disengagement · proactive outreach recommended",
      similarCases: 9,
      age: "yesterday",
    },
    {
      id: "AL-013",
      severity: "LOW",
      athlete: "Carla Roth",
      aid: "a8",
      type: "Goal deadline",
      title: "Body comp goal · 14 days remaining · 78% complete",
      why: "On pace but margin shrinking. Worth a check-in.",
      confidence: 0.55,
      fpRisk: 0.3,
      predicted: "Likely to miss target by 2-3 percentage points if pace holds",
      similarCases: 5,
      age: "yesterday",
    },
    {
      id: "AL-012",
      severity: "INFO",
      athlete: "Marcus Weber",
      aid: "a3",
      type: "PR achieved",
      title: "Deadlift PR · 220 kg ×1 (previous 215 kg)",
      why: "Block 4 progression on schedule. Form rating 4.8/5 from auto-check.",
      confidence: 1,
      fpRisk: 0,
      predicted: "Celebration + bench progression unlock recommended",
      similarCases: null,
      age: "today 06:30",
    },
  ] as const

/** `extras.jsx` · `COACH_ROLES` */
export const COACH_ROLES = [
    {
      id: "head",
      label: "Head Coach",
      caps: { all: true, billing: true, team: true, advAnalytics: true },
    },
    {
      id: "senior",
      label: "Senior Coach",
      caps: { assignedPlusTeam: true, dataExport: true, ownRules: true, stdAnalytics: true },
    },
    {
      id: "coach",
      label: "Coach",
      caps: { assignedOnly: true, dataExportLimited: true, templatesOnly: true, basicAnalytics: true },
    },
  ] as const

/** `extras.jsx` · `TEAM_MEMBERS` */
export const TEAM_MEMBERS = [
    { id: "tm1", name: "Tom Müller (you)", role: "head", athletes: 14, since: "2 yr", rating: 4.9 },
    { id: "tm2", name: "Erik Lange", role: "senior", athletes: 8, since: "1 yr", rating: 4.7 },
    { id: "tm3", name: "Hanna Brodersen", role: "senior", athletes: 6, since: "8 mo", rating: 4.8 },
    { id: "tm4", name: "Paul Reinhardt", role: "coach", athletes: 4, since: "3 mo", rating: 4.5 },
    { id: "tm5", name: "Carla Vogt", role: "coach", athletes: 5, since: "5 mo", rating: 4.6 },
  ] as const

/** `extras.jsx` · `COACH_AUDIT` */
export const COACH_AUDIT = [
    {
      ts: "2026-05-16 14:22",
      who: "Tom (head)",
      action: "viewed Sophie Klein · Training",
      cat: "data-access",
    },
    {
      ts: "2026-05-16 11:48",
      who: "Hanna (senior)",
      action: "exported PDF report · Lukas Bauer",
      cat: "export",
    },
    {
      ts: "2026-05-16 09:14",
      who: "Tom (head)",
      action: "added rule \u0027Overtraining risk · 3-strike\u0027",
      cat: "rule",
    },
    { ts: "2026-05-15 17:32", who: "Paul (coach)", action: "messaged Niko Brandt", cat: "comm" },
    {
      ts: "2026-05-15 16:08",
      who: "Tom (head)",
      action: "promoted Sophie Klein autonomy 1 → 2",
      cat: "autonomy",
    },
    {
      ts: "2026-05-14 12:42",
      who: "Erik (senior)",
      action: "viewed Lea Hartmann · Recovery",
      cat: "data-access",
    },
    {
      ts: "2026-05-13 19:18",
      who: "Tom (head)",
      action: "approved Carla Vogt as Coach",
      cat: "team",
    },
    {
      ts: "2026-05-12 08:00",
      who: "system",
      action: "auto-fired alert AL-014 (Anna Frey)",
      cat: "alert",
    },
  ] as const

/** `extras.jsx` · `COACH_KPIS` */
export const COACH_KPIS = {
    retention90d: { value: 92, benchmark: 78, trend: "up" },
    satisfactionAvg: { value: 4.8, response: 0.84 },
    goalCompletion: { rate: 87, onTime: 71 },
    autonomyProgression: { avgLevelIncrease: 0.4, clientsProgressed: 6 },
    responseTime: { avg: 1.8, target: 4, percentile: 92 },
    alertResolution: { avg: 4.2, rate: 96 },
    proactiveInterventions: { count: 23, successRate: 78 },
    revenuePerClient: 344,
    ltv: 4280,
    referralRate: 0.21,
    expansion: 1840,
  } as const

/** `module-coach.jsx` · `COACHES` */
export const COACHES = [
    {
      id: "c-train",
      type: "Training",
      name: "Anders Lindqvist",
      title: "Strength · Periodization · S&C",
      org: "Performance Lab Stockholm",
      avatar: "AL",
      color: "var(--acc-train)",
      status: "active",
      since: "2024-08-12",
      sharedModules: ["Training", "Recovery", "Goals"],
      activePlan: "PPL · Block 3",
      lastMsg: "Bench at 117.5 felt heavy on set 4 — drop to 115 next session.",
      lastMsgAt: "Yesterday 21:14",
      unread: 0,
      cadence: "weekly · Mondays 19:00 CET",
      rating: 4.9,
      bio: "12 years coaching strength athletes. Former NSCA-CSCS. Periodization specialist.",
      fee: "€180 / month",
    },
    {
      id: "c-nutri",
      type: "Nutrition",
      name: "Jana Bauer",
      title: "Sports nutrition · DGE certified",
      org: "Independent · Berlin",
      avatar: "JB",
      color: "var(--acc-nutri)",
      status: "active",
      since: "2025-01-18",
      sharedModules: ["Nutrition", "Goals", "Supplements (MK-677 only)"],
      activePlan: "Recomp · 2,700 kcal split",
      lastMsg: "Increased carbs +20g on training days. Hold for 2 weeks then re-evaluate.",
      lastMsgAt: "Wed 18:42",
      unread: 1,
      cadence: "bi-weekly check-in · Wednesdays",
      rating: 4.8,
      bio: "Specialist for body recomposition. Whoop + DXA integration.",
      fee: "€120 / month",
    },
    {
      id: "c-med",
      type: "Medical",
      name: "Dr. Magnus Kessler",
      title: "Endokrinologe · Sport-Medicine",
      org: "Endokrinologie Berlin · Charlottenburg",
      avatar: "MK",
      color: "var(--acc-medic)",
      status: "active",
      since: "2024-09-12",
      sharedModules: ["Medical (full)", "Supplements (extended)", "Recovery (summary)"],
      activePlan: "TRT protocol · quarterly panels",
      lastMsg: "HCT 48% — within range. Continue current Test Cyp dose. Next panel Jul 15.",
      lastMsgAt: "Apr 23",
      unread: 0,
      cadence: "quarterly + ad-hoc",
      rating: 5,
      bio: "Certified endocrinologist. Sports-medicine focus. Member DGE/DGS.",
      fee: "€680 / year",
    },
    {
      id: "c-suppl",
      type: "Supplement",
      name: "David Park",
      title: "Performance nutrition · evidence-led",
      org: "Examine.com network · remote",
      avatar: "DP",
      color: "var(--acc-suppl)",
      status: "active",
      since: "2025-03-04",
      sharedModules: ["Supplements (full)", "Nutrition (summary)"],
      activePlan: "Stack v3.2 · 8 items",
      lastMsg: "Ashwagandha cycle off-week starts Jun 9. Reminder set.",
      lastMsgAt: "Mon 09:32",
      unread: 0,
      cadence: "monthly review",
      rating: 4.7,
      bio: "Peer-reviewed evidence approach. No upsell.",
      fee: "€60 / month",
    },
  ] as const

/** `module-coach.jsx` · `PENDING_INVITES` */
export const PENDING_INVITES = [
    {
      id: "inv-1",
      name: "Sarah Müller",
      type: "Physio",
      invitedOn: "May 12",
      expiry: "expires May 19",
    },
  ] as const

/** `module-coach.jsx` · `COACH_NOTES` */
export const COACH_NOTES = [
    {
      id: "n1",
      coach: "Anders Lindqvist",
      coachId: "c-train",
      module: "Training",
      date: "May 13",
      body: "Pull A · Wk2: PR on weighted pull-up at +30kg ×5. Consider deload week 4 already — RPE drifted above plan for 3 sessions.",
      tags: ["PR", "RPE-watch"],
    },
    {
      id: "n2",
      coach: "Jana Bauer",
      coachId: "c-nutri",
      module: "Nutrition",
      date: "May 8",
      body: "Add 200g sweet potato to Wed/Sat dinners. Compliance was 92% in April — strong baseline.",
      tags: ["adjustment"],
    },
    {
      id: "n3",
      coach: "Dr. M. Kessler",
      coachId: "c-med",
      module: "Medical",
      date: "Apr 23",
      body: "All TRT markers stable. Watch Hematocrit if it climbs above 49 — donate blood next quarter as preventive.",
      tags: ["TRT", "monitor"],
    },
    {
      id: "n4",
      coach: "Anders Lindqvist",
      coachId: "c-train",
      module: "Training",
      date: "May 6",
      body: "Move Push B from 18:00 to 16:30 next block — Buddy correlation supports it. Will coordinate with Jana on pre-workout meal.",
      tags: ["cross-coach"],
    },
    {
      id: "n5",
      coach: "David Park",
      coachId: "c-suppl",
      module: "Supplements",
      date: "Apr 28",
      body: "MK-677 baseline panel done. Track fasting glucose. Cycle off if exceeds 110 mg/dL.",
      tags: ["MK-677", "safety"],
    },
  ] as const

/** `module-coach.jsx` · `PORTAL_ATHLETES` */
export const PORTAL_ATHLETES = [
    {
      id: "a1",
      name: "Lukas Bauer",
      avatar: "LB",
      since: "2y 1mo",
      plan: "PPL · Block 3",
      compliance: 98,
      alerts: 0,
      lastSession: "today 07:14",
      tags: ["pro", "powerlifter"],
    },
    {
      id: "a2",
      name: "Sophie Klein",
      avatar: "SK",
      since: "8mo",
      plan: "Upper-Lower Hyper",
      compliance: 89,
      alerts: 1,
      lastSession: "yesterday",
      tags: ["recreational"],
    },
    {
      id: "a3",
      name: "Marcus Weber",
      avatar: "MW",
      since: "1y 6mo",
      plan: "5/3/1 BBB · Wk 4",
      compliance: 100,
      alerts: 0,
      lastSession: "today 06:30",
      tags: ["pro"],
    },
    {
      id: "a4",
      name: "Elena Schmidt",
      avatar: "ES",
      since: "3mo",
      plan: "Beginner Linear",
      compliance: 76,
      alerts: 2,
      lastSession: "3d ago",
      tags: ["beginner"],
    },
    {
      id: "a5",
      name: "Niko Brandt",
      avatar: "NB",
      since: "2y 4mo",
      plan: "Powerbuilding · Custom",
      compliance: 94,
      alerts: 0,
      lastSession: "today",
      tags: ["pro"],
    },
    {
      id: "a6",
      name: "Lea Hartmann",
      avatar: "LH",
      since: "1y 2mo",
      plan: "PPL · Block 2",
      compliance: 92,
      alerts: 1,
      lastSession: "yesterday",
      tags: ["intermediate"],
    },
    {
      id: "a7",
      name: "Felix Krause",
      avatar: "FK",
      since: "10mo",
      plan: "Full Body 3x",
      compliance: 84,
      alerts: 0,
      lastSession: "2d ago",
      tags: ["recreational"],
    },
    {
      id: "a8",
      name: "Carla Roth",
      avatar: "CR",
      since: "4mo",
      plan: "Hypertrophy · Wk 6",
      compliance: 95,
      alerts: 0,
      lastSession: "today 17:08",
      tags: ["intermediate"],
    },
    {
      id: "a9",
      name: "Daniel Vogel",
      avatar: "DV",
      since: "1y 8mo",
      plan: "Conjugate · Block 2",
      compliance: 88,
      alerts: 2,
      lastSession: "yesterday",
      tags: ["pro", "powerlifter"],
    },
    {
      id: "a10",
      name: "Mira Stahl",
      avatar: "MS",
      since: "6mo",
      plan: "Strength 5x",
      compliance: 81,
      alerts: 1,
      lastSession: "today 19:42",
      tags: ["intermediate"],
    },
    {
      id: "a11",
      name: "Jonas Becker",
      avatar: "JB",
      since: "2y 9mo",
      plan: "Periodized · Marathon",
      compliance: 96,
      alerts: 0,
      lastSession: "today",
      tags: ["endurance"],
    },
    {
      id: "a12",
      name: "Anna Frey",
      avatar: "AF",
      since: "1y",
      plan: "PPL · Block 1",
      compliance: 79,
      alerts: 1,
      lastSession: "4d ago",
      tags: ["intermediate"],
    },
    {
      id: "a13",
      name: "Tom Müller",
      avatar: "TM",
      since: "9mo",
      plan: "PPL · Block 3 (current)",
      compliance: 94,
      alerts: 0,
      lastSession: "today 06:50",
      tags: ["self"],
    },
    {
      id: "a14",
      name: "Erik Lange",
      avatar: "EL",
      since: "5mo",
      plan: "Beginner Linear",
      compliance: 91,
      alerts: 0,
      lastSession: "today",
      tags: ["beginner"],
    },
  ] as const

/** `module-coach.jsx` · `COACH_PLANS` */
export const COACH_PLANS = [
    {
      id: "p1",
      name: "PPL · Hypertrophy → Strength · 5 weeks",
      category: "Training",
      assignedTo: 6,
      sells: 18,
      rating: 4.9,
      lastUpdated: "Apr 14",
    },
    {
      id: "p2",
      name: "5/3/1 BBB · 12 weeks",
      category: "Training",
      assignedTo: 4,
      sells: 22,
      rating: 4.8,
      lastUpdated: "Mar 22",
    },
    {
      id: "p3",
      name: "Upper-Lower Hypertrophy · 6 weeks",
      category: "Training",
      assignedTo: 3,
      sells: 11,
      rating: 4.7,
      lastUpdated: "Feb 8",
    },
    {
      id: "p4",
      name: "Conjugate · 8 weeks (powerlifting)",
      category: "Training",
      assignedTo: 2,
      sells: 8,
      rating: 4.9,
      lastUpdated: "Mar 1",
    },
    {
      id: "p5",
      name: "Beginner Linear · 12 weeks",
      category: "Training",
      assignedTo: 5,
      sells: 41,
      rating: 4.6,
      lastUpdated: "Jan 18",
    },
    {
      id: "p6",
      name: "Marathon prep · 16 weeks",
      category: "Endurance",
      assignedTo: 1,
      sells: 6,
      rating: 4.7,
      lastUpdated: "Feb 14",
    },
  ] as const

/** `module-coach.jsx` · `MESSAGES_THREAD` */
export const MESSAGES_THREAD = [
    {
      id: "m1",
      from: "Anders",
      at: "Yesterday 21:14",
      body: "Bench at 117.5 felt heavy on set 4 — drop to 115 next session.",
      direction: "in",
    },
    {
      id: "m2",
      from: "Tom",
      at: "Yesterday 21:18",
      body: "Will do. Felt the slow rep on 4. Going for 5×5 next Mon.",
      direction: "out",
    },
    {
      id: "m3",
      from: "Anders",
      at: "Yesterday 21:22",
      body: "Good. Send a video if you want me to check bar path on the last attempt.",
      direction: "in",
    },
    {
      id: "m4",
      from: "Anders",
      at: "May 10 09:14",
      body: "Pull-up PR. Nice work. Recovery numbers were perfect this week.",
      direction: "in",
    },
    {
      id: "m5",
      from: "Tom",
      at: "May 10 11:32",
      body: "Cheers. Felt the lats more than usual — RPE 8.",
      direction: "out",
    },
  ] as const
