-- C-393: Der Schreiber zu C-327 ist als deploybare Migration vorhanden.
-- Die acht Zuordnungen bleiben ausschliesslich aus wr_chelation_timing abgeleitet.
-- Der abgeleitete Bestand entsteht in 327a_chelation_mineral_membership.sql.
